### ISSUE TITLE
关于报错信息

### ISSUE THREAD

**Issue by TitaniumOne** [01joy/news-search-engine#5]
请问这个是什么原因呀？如何解决呢
```
[2020-12-04 23:31:35,467] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\SoftWare\Tools\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\SoftWare\Tools\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\SoftWare\Tools\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\SoftWare\Tools\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\SoftWare\Tools\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\SoftWare\Tools\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Data\master_course\��Ϣ�����������ھ�\news-search-engine\web\main.py", line 33, in main
    init()
  File "c:\Data\master_course\��Ϣ�����������ھ�\news-search-engine\web\main.py", line 27, in init
    dir_path = config['DEFAULT']['doc_dir_path']
  File "C:\SoftWare\Tools\Python38\lib\configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'doc_dir_path'
```

**Comment by 01joy** [comment]
看错误信息好像是config.ini里面少了参数doc_dir_path

**Comment by TitaniumOne** [comment]
谢谢您的回复！我解决了这个问题。但是运行main.py时，输入关键词后，无法返回输出结果，如果有时间可否帮我看一下？万分感谢！
```
search error
[2020-12-06 18:13:51,594] ERROR in app: Exception on /search/ [POST]
Traceback (most recent call last):
  File "C:\SoftWare\Tools\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\SoftWare\Tools\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\SoftWare\Tools\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\SoftWare\Tools\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
```
```
前端返回的信息是这样：
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by TitaniumOne** [comment]
谢谢您！代码写的很好！
